language: objective-c
osx_image: xcode8

env:
  - ACTION=test PLATFORM=iOS  DESTINATION='platform=iOS Simulator,name=iPhone 6S' UUID='7FC06F6D-AF72-4B38-9A96-1F934EA2E27F'
  - ACTION=test PLATFORM=tvOS DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p' UUID='0DF1B136-A3A7-4C51-AE6E-CFEFDF52DA24'

install:
  - carthage bootstrap --platform $PLATFORM

script:
  - if [ -n "$UUID" ]; then xcrun instruments -w "$UUID" || true; sleep 15; fi
  - set -o pipefail && xcodebuild -scheme PMKPhotos -destination "$DESTINATION" $ACTION | xcpretty
