language: objective-c
osx_image: xcode8

env:
  - PLATFORM=Mac
  - PLATFORM=iOS NAME='iPhone SE'
  - PLATFORM=tvOS NAME='Apple TV 1080p'
  - PLATFORM=watchOS

before_install:
  - if [ -n "$NAME" ]; then
      export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /$NAME .* \[(.*)\]/; if \$1; puts(\$1); exit; end }");
    fi

install:
  - carthage bootstrap --platform $PLATFORM

script:
  - set -o pipefail;
    case $PLATFORM in
    Mac)
      xcodebuild -scheme PMKAlamofire test | xcpretty;;
    iOS|tvOS)
      xcrun instruments -w "$UUID" || true;
      sleep 15;
      xcodebuild -scheme PMKAlamofire -destination "id=$UUID" test | xcpretty;;
    watchOS)
      xcodebuild -scheme PMKAlamofire -destination "name=Apple Watch - 38mm" | xcpretty;;
    esac
